### ISSUE TITLE
Couldn't parse LABELS

### ISSUE THREAD

**Issue by Sceat** [RedisTimeSeries/prometheus-redistimeseries-adapter#123]
Using this adapter and prometheus in a kubernetes deployment, I get

```
│ time="2024-07-11T14:27:04Z" level=warning msg="Could not send samples to remote storage" err="ERR TSDB: Couldn't parse LABELS" num_samples=500 storage=RedisTS                             │
```

Which would indicate prometheus or the adapter is trying to submit wrong labels (maybe including commas?)

**Comment by Sceat** [comment]
using this fixed it

```
      metric_relabel_configs:
        - source_labels: [__name__, job, instance]
          regex: '(.*)'
          replacement: '${1//,/ }'
          target_label: instance
```
